# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='date',
            new_name='creation',
        ),
    ]
