# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mnemo', models.CharField(max_length=15, unique=True, verbose_name='Mnemonique')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('naissance', models.DateField(verbose_name='Date de naissance')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Solde')),
                ('sexe', models.CharField(choices=[('HO', 'Homme'), ('FE', 'Femme')], max_length=2)),
                ('niveau', models.CharField(choices=[('MINI', 'MINI'), ('NOVICE', 'NOVICE'), ('TOP', 'TOP')], max_length=7)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemo', models.CharField(max_length=15, unique=True, verbose_name='Mnemonique')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('naissance', models.DateField(verbose_name='Date de naissance')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Solde')),
                ('sexe', models.CharField(choices=[('HO', 'Homme'), ('FE', 'Femme')], max_length=2)),
                ('niveau', models.CharField(choices=[('MINI', 'MINI'), ('NOVICE', 'NOVICE'), ('TOP', 'TOP')], max_length=7)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateDemande', models.DateField(auto_now=True, verbose_name='Date de la demande')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Montant de la demande')),
                ('dateReponse', models.DateField(blank=True, null=True, verbose_name='Date de réponse')),
                ('accepte', models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=2)),
                ('clientDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientsDemandeurs', to='client.Compte', verbose_name='Client demandeur')),
                ('clientReceveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientsReceveurs', to='client.Compte', verbose_name='Client receveur')),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Mode', verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='compte',
            name='modePrefere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modePrefere', to='client.Mode', verbose_name='Mode de remboursement préféré'),
        ),
        migrations.AddField(
            model_name='compte',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
