# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='accepte',
            field=models.CharField(blank=True, choices=[('En attente', 'En attente'), ('OUI', 'Oui'), ('NON', 'Non')], max_length=2),
        ),
    ]
