# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160725_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='accepte',
        ),
        migrations.AddField(
            model_name='demande',
            name='etat',
            field=models.CharField(blank=True, choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], max_length=2),
        ),
    ]
