# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160725_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='etat',
            field=models.CharField(blank=True, choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], max_length=20),
        ),
    ]
