# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20160725_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='etat',
            field=models.CharField(blank=True, choices=[('E', 'En attente'), ('A', 'Acceptée'), ('R', 'Refusée')], max_length=20),
        ),
    ]
