# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0006_auto_20160427_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemo', models.CharField(max_length=15, unique=True, verbose_name='Mnemonique')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('naissance', models.DateField(verbose_name='Date de naissance')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Solde')),
                ('sexe', models.CharField(choices=[('HO', 'Homme'), ('FE', 'Femme')], max_length=2)),
                ('niveau', models.CharField(choices=[('MINI', 'MINI'), ('NOVICE', 'NOVICE'), ('TOP', 'TOP')], max_length=7)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
