# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_demande_commentaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='compte',
            name='niveau',
            field=models.CharField(blank=True, choices=[('MINI', 'MINI'), ('NOVICE', 'NOVICE'), ('TOP', 'TOP')], max_length=7, null=True),
        ),
    ]
