# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20160729_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='niveau',
            field=models.CharField(choices=[('MINI', 'MINI'), ('NOVICE', 'NOVICE'), ('TOP', 'TOP')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
