# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20160729_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
            ],
        ),
    ]
