# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_compte_modeprefere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='clientDemandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientsDemandeurs', to='client.Compte', verbose_name='Client demandeur'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='clientReceveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientsReceveurs', to='client.Compte', verbose_name='Client receveur'),
        ),
    ]
