# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20160729_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=20),
        ),
    ]
