# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20160729_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name_plural': 'Niveaux'},
        ),
    ]
