# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20160729_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='etat',
            field=models.CharField(blank=True, choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], max_length=20),
        ),
    ]
