# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_remove_compte_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='nbTransactionMinimum',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
