# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_niveau_nbtransactionminimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='nbTransactionMinimum',
            field=models.IntegerField(default=1, verbose_name='Nombre de transactions minimum'),
            preserve_default=False,
        ),
    ]
