# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_auto_20160818_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='rabais',
            field=models.IntegerField(default=0, verbose_name='Rabais (en %)'),
            preserve_default=False,
        ),
    ]
