# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glace',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prixVenteConseille',
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.CharField(choices=[('AD', 'Admin')], default='AD', max_length=50, verbose_name='Fournisseur'),
        ),
        migrations.DeleteModel(
            name='Glace',
        ),
    ]
