# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0002_auto_20160725_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prixVente',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='Prix de vente'),
            preserve_default=False,
        ),
    ]
