# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0003_produit_prixvente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='bac',
        ),
        migrations.AddField(
            model_name='bac',
            name='capaciteMax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Capacité maximum'),
        ),
        migrations.AddField(
            model_name='bac',
            name='nbProduit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Nombre de produits actuel'),
        ),
    ]
