# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0004_auto_20160726_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibelleGlace',
        ),
    ]
