# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0010_auto_20160726_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='bac',
            field=models.ManyToManyField(blank=True, null=True, related_name='produits', to='congelateur.Bac'),
        ),
    ]
