# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0011_auto_20160726_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Quantité du mouvement')),
                ('bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congelateur.Bac')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congelateur.Produit')),
            ],
        ),
    ]
