# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0012_mouvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvement',
            name='bac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bac', to='congelateur.Bac'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produit', to='congelateur.Produit'),
        ),
    ]
