# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0013_auto_20160729_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='stockRestant',
        ),
    ]
