# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0014_remove_produit_stockrestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stockRestant',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
