# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0015_produit_stockrestant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prixVente',
            new_name='prixDeVente',
        ),
    ]
