# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0016_auto_20160806_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prixDeVente',
            new_name='prixVente',
        ),
    ]
