# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0017_auto_20160806_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prixVente',
            new_name='prixvente',
        ),
    ]
