# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0018_auto_20160806_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prixvente',
            new_name='prixVente',
        ),
    ]
