# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0019_auto_20160806_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='bac',
            field=models.ManyToManyField(blank=True, related_name='produits', to='congelateur.Bac'),
        ),
    ]
