# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0021_glace_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glace',
            old_name='type',
            new_name='statut',
        ),
    ]
