# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0022_auto_20160607_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibelleGlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé de la glace')),
            ],
        ),
    ]
