# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0023_libelleglace'),
    ]

    operations = [
        migrations.AddField(
            model_name='glace',
            name='testLibelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congelateur.LibelleGlace', verbose_name='Libellé'),
        ),
    ]
