# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0024_glace_testlibelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glace',
            name='testLibelle',
        ),
        migrations.AlterField(
            model_name='glace',
            name='libelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congelateur.LibelleGlace', verbose_name='Libellé'),
        ),
    ]
