# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0026_auto_20160718_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glacee',
            name='datePeremption',
            field=models.DateField(verbose_name='Date de péremption'),
        ),
    ]
