# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0027_auto_20160718_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='libelle',
            field=models.CharField(max_length=150, verbose_name='Libellé de la glace'),
        ),
    ]
