# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0028_auto_20160718_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stockRestant',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
