# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0029_produit_stockrestant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glacee',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='glace',
            name='bac',
        ),
        migrations.RemoveField(
            model_name='glace',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='glace',
            name='image',
        ),
        migrations.RemoveField(
            model_name='glace',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='glace',
            name='prixVente',
        ),
        migrations.RemoveField(
            model_name='glace',
            name='statut',
        ),
        migrations.AddField(
            model_name='glace',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='glaces', to='congelateur.Produit', verbose_name='Produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glace',
            name='datePeremption',
            field=models.DateField(verbose_name='Date de péremption'),
        ),
        migrations.DeleteModel(
            name='Glacee',
        ),
    ]
