# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0030_auto_20160718_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glace',
            name='calories',
        ),
        migrations.AddField(
            model_name='produit',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Callories'),
        ),
    ]
