# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0031_auto_20160718_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='bac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='congelateur.Bac', verbose_name='Bac ou trouver la glace'),
            preserve_default=False,
        ),
    ]
