# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congelateur', '0004_auto_20160726_0957'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Montant de la ligne')),
                ('glace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glace', to='congelateur.Produit', verbose_name='Glace de la transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date de la transaction')),
                ('type', models.CharField(choices=[('A', 'Achat'), ('R', 'Réapprovisionnement')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transactions', verbose_name='Image')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total de transaction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Client de la transaction')),
            ],
        ),
        migrations.AddField(
            model_name='lignetransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='transaction.Transaction', verbose_name='Transaction'),
        ),
    ]
