# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignetransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='transaction.Transaction', verbose_name='Transaction'),
        ),
    ]
