# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignetransaction',
            old_name='glace',
            new_name='produit',
        ),
    ]
