# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20160520_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Total de transaction'),
            preserve_default=False,
        ),
    ]
