# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_lignetransaction_bac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignetransaction',
            name='bac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bacsLignes', to='congelateur.Bac', verbose_name='bac de la ligne'),
        ),
    ]
