# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20160607_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignetransaction',
            name='glace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glace', to='congelateur.Produit', verbose_name='Glace de la transaction'),
        ),
    ]
