# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20160718_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 7, 21, 7, 26, 56, 276962, tzinfo=utc), verbose_name='Date de la transaction'),
            preserve_default=False,
        ),
    ]
