# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0008_remove_produit_bac'),
        ('transaction', '0005_remove_lignetransaction_bac'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignetransaction',
            name='bac',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bacsLignes', to='congelateur.Bac', verbose_name='bac de la ligne'),
            preserve_default=False,
        ),
    ]
