# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_lignetransaction_bac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignetransaction',
            name='bac',
        ),
    ]
