# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_lignetransaction_bac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Achat', 'Achat'), ('Réapprovisionnement', 'Réapprovisionnement')], max_length=2),
        ),
    ]
