# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20160801_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Client de la transaction'),
        ),
    ]
