# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20160801_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Achat', 'Achat'), ('Réapprovisionnement', 'Réapprovisionnement'), ('Admin', 'Admin')], max_length=30),
        ),
    ]
