# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_remove_compte_role'),
        ('transaction', '0014_transactionannexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionannexe',
            name='clientTouche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Compte'),
        ),
    ]
