# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_transactionannexe_clienttouche'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionannexe',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 5, 14, 32, 9, 291530, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionannexe',
            name='clientTouche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Compte', verbose_name='Client'),
        ),
    ]
